# Generated by Django 3.2.5 on 2021-07-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='benchType',
        ),
        migrations.DeleteModel(
            name='direction',
        ),
    ]
